In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

data = pd.read_csv("new_dataset.csv")            #Loading the Data
data

,estimated_stock_pct,quantity,temperature,unit_price,day_of_month,day_of_week,hour,category_baby products,category_baked goods,category_baking,...,category_meat,category_medicine,category_packaged foods,category_personal care,category_pets,category_refrigerated items,category_seafood,category_snacks,category_spices and herbs,category_vegetables
0,0.89,3,-0.028850,11.19,1,1,9,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0.14,3,-0.028850,1.49,1,1,9,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0.67,0,-0.028850,14.19,1,1,9,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0.00,0,-0.028850,7.99,1,1,9,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0.82,0,-0.028850,20.19,1,1,9,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23095,0.00,0,-0.165077,14.19,7,0,19,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23096,0.00,0,-0.165077,15.49,7,0,19,0,0,0,...,0,1,0,0,0,0,0,0,0,0
23097,0.00,0,-0.165077,0.19,7,0,19,0,0,0,...,0,0,0,0,0,0,0,0,1,0
23098,0.00,1,-0.165077,7.99,7,0,19,0,0,1,...,0,0,0,0,0,0,0,0,0,0
23099,0.00,1,-0.165077,3.19,7,0,19,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [5]:
'''Creating a split function that'll split the dataset into target variable and 
training dataset'''
def create_target_and_predictors(
    data: pd.DataFrame = None, 
    target: str = "estimated_stock_pct"
):
    X = data.drop(columns=[target]).    #These two sets of data will train the supervised ML Models
    y = data[target]
    return X, y

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler

'''Creating a function that'll take in the two sets of data
and create a Random Forest Supervised Machine Learning Model
validating it through K Fold Cross Validation and evaluating
its performance over various performance metrics'''

def train_algorithm_with_cross_validation(
    X: pd.DataFrame = None, 
    y: pd.Series = None
):

#Creating a list to store accuracy of each fold
    accuracy = []
    
#Creating a loop to enter into K folds of Cross Validation such that K = 10
    for fold in range (0, 10):

        x = data.drop('estimated_stock_pct', axis = 1)
        y = data['estimated_stock_pct']
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)   #Creating Training and test samples
        
    # Instantiate algorithm and scaler
        model = RandomForestRegressor()
        scaler = StandardScaler()

    # Scale X data, we scale the data because it helps the algorithm to converge
    # and helps the algorithm to not be greedy with large values
        scaler.fit(x_train)
        x_train = scaler.transform(x_train)
        x_test = scaler.transform(x_test)

        model.fit(x_train, y_train)                   #Training the model
        y_predict = model.predict(x_test)             #Generating Predictions on Test Sample

        mse = mean_squared_error(y_test, y_predict)   #Computing Accuarcy
        r2 = r2_score(y_test, y_predict)

        print(f"Mean Squared Error = {mse}")        
        print(f"R2 Score = {r2}")

        mae = mean_absolute_error(y_true=y_test, y_pred=y_predict)
        accuracy.append(mae)
        print(f"Fold {fold + 1}: MAE = {mae:.3f}")

# Finish by computing the average MAE across all folds
    print(f"Average MAE: {(sum(accuracy) / len(accuracy)):.2f}")